### ISSUE TITLE
Can you make Japanese Ver.

### ISSUE THREAD

**Issue by massan16** [RyoLee/UmaCruise-U#1]
I find this customized version to be much easier to use. If you can afford it, could you please make a version in Japanese?

**Comment by RyoLee** [comment]
for UI: the i18n support will be added in the next 2 or 3 updates.
for data: IDK. because the upstream data I used was already be modified in some way. (like some kanji were covered to Chinese characters) so probably I will give a JP version, but with no verify.

**Comment by massan16** [comment]
thank you and best regards

**Comment by massan16** [comment]
Thank you for implementing this.
I have translated to JP it in my own way, so please use it if you can include it.
I couldn't think of a good translation for "Function", so I left it blank.
Thank you very much.
[ja_jp.txt](https://github.com/RyoLee/UmaCruise-U/files/6789265/ja_jp.txt)
