### ISSUE TITLE
版本检测失败，数据更新失败

### ISSUE THREAD

**Issue by AriadusTT** [RyoLee/UmaCruise-U#2]
版本检测失败，数据更新失败
失败info内容均为
[error]: HttpSendRequestAndReceiveResponse - WinHttpSendRequest Error!: 12030

**Comment by RyoLee** [comment]
UmaLibrary\Common.json 配置里用的是jsdelivr的CDN,这家年初的时候国内备案被摘了,最近几个月时不时吃墙,所以可能会有一些网络访问上的问题,虽然我还知道几个其他的镜像站,但是这个还是治标不治本的,现在github镜像都是随时可能被墙的状态
